const products = [{ id: 1, name: 'Laptop Pro 15"', price: 1299.99 }, { id: 2, name: 'Smartphone Max', price: 899.99 }, { id: 3, name: 'Tablet Air 12"', price: 599.99 }, { id: 4, name: 'Auriculares Premium', price: 249.99 }, { id: 5, name: 'Smartwatch Ultra', price: 399.99 }, { id: 6, name: 'Cámara Digital Pro', price: 1199.99 }];
let cart = [];
function addToCart(productId) { const product = products.find(p => p.id === productId); if (product) { const existingItem = cart.find(item => item.id === productId); if (existingItem) { existingItem.quantity++; } else { cart.push({ ...product, quantity: 1 }); } updateCart(); showNotification(`${product.name} agregado al carrito`); } }
function removeFromCart(productId) { cart = cart.filter(item => item.id !== productId); updateCart(); }
function updateCart() { const cartItems = document.getElementById('cartItems'); const totalPrice = document.getElementById('totalPrice'); if (cart.length === 0) { cartItems.innerHTML = '<p class="empty-cart">Tu carrito está vacío</p>'; if (totalPrice) totalPrice.textContent = '0.00'; return; } cartItems.innerHTML = cart.map(item => `<div class="cart-item"><h4>${item.name}</h4><p>Precio: $${item.price.toFixed(2)}</p><p>Cantidad: ${item.quantity}</p><p><strong>Subtotal: $${(item.price * item.quantity).toFixed(2)}</strong></p><button onclick="removeFromCart(${item.id})" class="btn" style="background-color: #dc3545; margin: 0.5rem 0;">Eliminar</button></div><hr>`).join(''); const total = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0); if (totalPrice) totalPrice.textContent = total.toFixed(2); }
const contactForm = document.getElementById('contactForm'); if (contactForm) { contactForm.addEventListener('submit', function(e) { e.preventDefault(); const nombre = document.getElementById('nombre').value; const email = document.getElementById('email').value; const asunto = document.getElementById('asunto').value; const mensaje = document.getElementById('mensaje').value; if (!nombre || !email || !asunto || !mensaje) { showFormMessage('Por favor completa todos los campos', 'error', 'formMessage'); return; } setTimeout(() => { showFormMessage('¡Mensaje enviado correctamente! Nos pondremos en contacto pronto.', 'success', 'formMessage'); contactForm.reset(); }, 1000); }); }
const checkoutForm = document.getElementById('checkoutForm'); if (checkoutForm) { const paymentMethods = document.querySelectorAll('input[name="paymentMethod"]'); paymentMethods.forEach(method => { method.addEventListener('change', function() { const paymentDetails = document.getElementById('paymentDetails'); if (this.value === 'transferencia') { paymentDetails.innerHTML = '<h4>Instrucciones de Transferencia</h4><p><strong>Banco:</strong> Banamex</p><p><strong>Cuenta:</strong> 123456789</p>'; } else if (this.value === 'tarjeta') { paymentDetails.innerHTML = '<h4>Información de Tarjeta</h4><p>Ingresa datos de tu tarjeta de crédito o débito.</p>'; } else if (this.value === 'paypal') { paymentDetails.innerHTML = '<h4>PayPal</h4><p>Serás redirigido a PayPal para completar el pago.</p>'; } }); }); checkoutForm.addEventListener('submit', function(e) { e.preventDefault(); const fullname = document.getElementById('fullname').value; const email = document.getElementById('checkout-email').value; const paymentMethod = document.querySelector('input[name="paymentMethod"]:checked'); if (!fullname || !email || !paymentMethod) { showFormMessage('Por favor completa todos los campos', 'error', 'checkoutMessage'); return; } if (cart.length === 0) { showFormMessage('Tu carrito está vacío', 'error', 'checkoutMessage'); return; } const checkoutMessage = document.getElementById('checkoutMessage'); checkoutMessage.textContent = 'Procesando tu compra...'; checkoutMessage.className = 'checkout-message'; checkoutMessage.style.display = 'block'; setTimeout(() => { const total = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0); checkoutMessage.innerHTML = `<strong>¡Compra realizada exitosamente!</strong><br>Número de orden: #${Math.floor(Math.random() * 1000000)}<br>Total: $${total.toFixed(2)}`; checkoutMessage.className = 'checkout-message success'; cart = []; updateCart(); checkoutForm.reset(); }, 2000); }); }
function showFormMessage(message, type, elementId) { const element = document.getElementById(elementId); if (element) { element.textContent = message; element.className = `${elementId} ${type}`; element.style.display = 'block'; setTimeout(() => { element.style.display = 'none'; }, 5000); } }
function showNotification(message) { const notification = document.createElement('div'); notification.textContent = message; notification.style.cssText = 'position: fixed; top: 20px; right: 20px; background-color: #28a745; color: white; padding: 1rem 1.5rem; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2); z-index: 1000; animation: slideIn 0.3s ease;'; document.body.appendChild(notification); setTimeout(() => { notification.style.animation = 'slideOut 0.3s ease'; setTimeout(() => notification.remove(), 300); }, 3000); }
const style = document.createElement('style'); style.textContent = '@keyframes slideIn { from { transform: translateX(400px); opacity: 0; } to { transform: translateX(0); opacity: 1; } } @keyframes slideOut { from { transform: translateX(0); opacity: 1; } to { transform: translateX(400px); opacity: 0; } }'; document.head.appendChild(style);
document.addEventListener('DOMContentLoaded', function() { updateCart(); console.log('✅ TechStore - Página web cargada exitosamente'); });
function validateEmail(email) { const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; return regex.test(email); }
const emailInputs = document.querySelectorAll('input[type="email"]'); emailInputs.forEach(input => { input.addEventListener('blur', function() { if (this.value && !validateEmail(this.value)) { this.style.borderColor = '#dc3545'; } else { this.style.borderColor = '#ddd'; } }); });